// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/sisco#4chan

static const uint32_t dsp_descriptor_id = 6;
static const uint32_t gui_descriptor_id = 0;
static const char *plugin_human_id = "Simple Scope (4 channel)";

const struct LV2Port ports[10] = {
  { "control", ATOM_IN, nan},
  { "notify", ATOM_OUT, nan},
  { "in1", AUDIO_IN, nan},
  { "out1", AUDIO_OUT, nan},
  { "in2", AUDIO_IN, nan},
  { "out2", AUDIO_OUT, nan},
  { "in3", AUDIO_IN, nan},
  { "out3", AUDIO_OUT, nan},
  { "in4", AUDIO_IN, nan},
  { "out4", AUDIO_OUT, nan},
};

static const uint32_t nports_total=10;
static const uint32_t nports_audio_in=4;
static const uint32_t nports_audio_out=4;
static const uint32_t nports_midi_in=0;
static const uint32_t nports_midi_out=0;
static const uint32_t nports_atom_in=1;
static const uint32_t nports_atom_out=1;
static const uint32_t nports_ctrl=0;
static const uint32_t nports_ctrl_in=0;
static const uint32_t nports_ctrl_out=0;
static const uint32_t min_atom_bufsiz=131616;
static const bool     send_time_info=false;
